const fs = require('fs');
const os = require('os');
const path = require('path');

const packageName = process.argv[2];
const packageRoot = `${process.cwd()}/packages/${packageName}`;
const packageJsonUrl = path.resolve(`${packageRoot}/package.json`);
const pjson = require(packageJsonUrl);

const content = `// this is autogenerated file, see version-update.js
export const VERSION = '${pjson.version}';
`;

const fileUrl = path.join(packageRoot, 'src', 'version.ts');
fs.writeFileSync(fileUrl, content.replace(/\n/g, os.EOL));
