'aws-sdk':
  # there are so many version to test, it can take forever.
  # we will just sample few of them
  versions: ">=2.880.0 || 2.706.0 || 2.608.0 || 2.518.0 || 2.422.0 || 2.315.0 || 2.224.1 || 2.122.0 || 2.59.0"
  commands:
    - yarn test
