name: PreRelease

on: 
  workflow_dispatch:

jobs:
  Publish:
    name: PreRelease
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Packages
        run: yarn install

      - name: Build
        run: yarn build

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: |
          yarn publish:ci:prerelease 0.0.0-$(date +"%Y-%m-%d--%H-%M")
