name: Publish

on: 
  workflow_dispatch:
    inputs:
      packageName:
        description: Which package to publish
        required: true
      semanticVersion:
        description: 'Semantic Version [major | minor | patch ]'
        required: true
        default: 'patch'

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          ref: 'master'

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Configure CI Git User
        run: |
          git config --global user.name '@aspecto-system'
          git config --global user.email 'aspecto-system@users.noreply.github.com'

      - name: Install node modules
        run: yarn --cwd packages/${{ github.event.inputs.packageName }}

      - name: Bump Version
        run: |
          yarn config set version-git-message "chore(release ${{ github.event.inputs.packageName }}) - publish v%s"
          yarn version --${{ github.event.inputs.semanticVersion }} --no-commit-hooks
          node version-update.js ${{ github.event.inputs.packageName }}

      - name: Build
        run: yarn --cwd packages/${{ github.event.inputs.packageName }} build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Changes
        run: /
          git add .
          git commit --amend --no-edit
          git push

