name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettier Check
        run: yarn prettier:check

  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

      neo4j:
        image: neo4j:4.2.3
        ports:
          - 7474:7474
          - 11011:7687
        env:
          NEO4J_AUTH: neo4j/test

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all history for all tags and branches
        run: git fetch

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build:ci

      - name: Test
        run: yarn test:ci:changed
