name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Start required docker containers for unit tests
        run: |
          docker run -d -p 27017:27017 -v ~/data:/data/db mongo &
          docker run --name testneo4j -p7474:7474 -p11011:7687 -d --env NEO4J_AUTH=neo4j/test neo4j:4.2.3 &
          wait

      - name: Test
        run: yarn test

    